### ISSUE TITLE
macOS 下截图失败

### ISSUE THREAD

**Issue by JeanLiDev** [sbfkcel/WechatJumpGameHelper#3]
macOS 10.13.2系统版本,照着做一切正常,可是微信打开跳一跳后,网页没有反应,终端提醒截图失败.是安卓连Mac传文件的问题?如果是这个问题我已经解决了,那是什么原因呢?

**Comment by sbfkcel** [comment]
连接好之后，打开微信跳一跳，网页要手动刷新

**Comment by sbfkcel** [comment]
截图失败，确认下你的手机是否已经打开调试模式。
