### ISSUE TITLE
分数没有上传到排行榜

### ISSUE THREAD

**Issue by huangcan5421** [sbfkcel/WechatJumpGameHelper#5]
本地排行榜已经更新了 但是其他人的排行榜没有 然后 再跳分数也不更新了 - -

**Comment by sbfkcel** [comment]
你是不是之前刷过？别刷 得被官方查到，否则可能会被清零或分数提交不了。这种情况可能需要过阵子等你帐号解封了才行。

辅助工具本身不对游戏数据作任何操作。此时你手动玩应该也提交不了分数的。

**Comment by huangcan5421** [comment]
是的 我看你最近更新了模拟手动操作 之前没有 我是之前版本跑过一次 手动跳也没分数了

**Comment by sbfkcel** [comment]
等你手动玩了能加分可以再刷。记得别万别刷 太多~~400分不能再多了。400+的都很容易被封杀。我就是为了测试DEMO刷 到4K+搞过份了，哈哈。
