### ISSUE TITLE
使用时报错

### ISSUE THREAD

**Issue by haishengXie0712** [sbfkcel/WechatJumpGameHelper#7]
error
屏幕分辩率获取出错
请检查手机是否已经成功连接电脑并已经开启USB调试模式

**Comment by sbfkcel** [comment]
应该是你USB接口或设置存在问题。通常有：

- USB调试模式是否打开？
- 电脑是否已经安装好相关驱动（win7以上的操作系统一般会自动安装，可能需要稍微等待）
- 电脑是否被授权调试（连接好电脑之后，手机上会弹出一个确认框，选择授权信任即可）
- USB的接口是否稳定，建议插在电脑的后置USB的产品（一些前置的接口不稳定）

**Comment by sbfkcel** [comment]
![errorhelp](https://user-images.githubusercontent.com/5469785/34868730-b73cbeac-f7bf-11e7-9a92-4a121d7c3bec.png)

**Comment by haishengXie0712** [comment]
已经好了，谢谢
